# Generated by Django 3.2.12 on 2023-02-13 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('nameEn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（英文）')),
                ('nameCn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（中文）')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('nameEn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（英文）')),
                ('nameCn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（中文）')),
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True, verbose_name='英文编号')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注')),
                ('port', models.PositiveIntegerField(db_index=True, default=8888, verbose_name='端口')),
                ('pwd', models.CharField(blank=True, max_length=48, null=True, verbose_name='root密码')),
                ('ttype', models.IntegerField(choices=[(0, 'MySQL'), (1, 'PostgreSQL')], db_index=True, default=0, verbose_name='数据库类型')),
            ],
            options={
                'verbose_name': '数据服务',
                'verbose_name_plural': '所有数据服务',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(max_length=40, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '电子邮箱',
                'verbose_name_plural': '所有电子邮箱',
            },
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('name', models.CharField(default='未知组', max_length=50, verbose_name='名称')),
            ],
            options={
                'verbose_name': '个体/组织',
                'verbose_name_plural': '所有个体/组织',
                'db_table': 'accountSystem_group',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('ip', models.GenericIPAddressField(help_text='可以是IPV4/IPV6', unique=True, verbose_name='IP地址')),
                ('rootUsername', models.CharField(default='root', max_length=32, verbose_name='root用户名')),
                ('rootPassword', models.CharField(max_length=32, null=True, verbose_name='root密码')),
                ('hoster', models.PositiveSmallIntegerField(choices=[(1, '阿里云'), (2, '腾讯云'), (3, '哈密市希望科技有限公司'), (4, '新疆丝路融创网络科技有限公司（局域网）')], null=True, verbose_name='托管方')),
                ('bios', models.CharField(blank=True, max_length=32, null=True, verbose_name='BIOS')),
                ('ssh', models.IntegerField(blank=True, default=22, verbose_name='SSH端口')),
                ('mac', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC地址')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属个体/组织')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '所有服务器',
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('nameEn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（英文）')),
                ('nameCn', models.CharField(default='', max_length=50, unique=True, verbose_name='名称（中文）')),
            ],
            options={
                'ordering': ['-updatedAt'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('content', models.CharField(blank=True, max_length=11, null=True, unique=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属个体/组织')),
            ],
            options={
                'verbose_name': '手机号',
                'verbose_name_plural': '所有手机号',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('name', models.CharField(default='未知类型', max_length=50, unique=True, verbose_name='名称')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站地址')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='', verbose_name='图标')),
            ],
            options={
                'verbose_name': '账号类型',
                'verbose_name_plural': '所有账号类型',
            },
        ),
        migrations.CreateModel(
            name='Wechat',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('id', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='微信号（ID）')),
                ('nickName', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('pwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='密码')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('email', models.OneToOneField(blank=True, help_text='你可以使用一验证过的邮箱地址登陆微信，也可以用它来找回微信密码', null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.email', verbose_name='绑定的邮箱')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属账号组')),
                ('tel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.tel', verbose_name='绑定的手机号')),
            ],
            options={
                'verbose_name': '微信',
                'verbose_name_plural': '所有微信',
            },
        ),
        migrations.CreateModel(
            name='ServerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('hasRootPriority', models.BooleanField(blank=True, default=False, verbose_name='拥有root权限')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属个体/组织')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.server', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '服务器用户',
                'verbose_name_plural': '所有服务器用户',
            },
        ),
        migrations.AddField(
            model_name='email',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属'),
        ),
        migrations.CreateModel(
            name='ElasticSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('remark', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='备注')),
                ('port', models.PositiveIntegerField(db_index=True, default=8888, verbose_name='端口')),
                ('elasticPwd', models.CharField(max_length=36, null=True, verbose_name='elastic')),
                ('kibanaPwd', models.CharField(blank=True, max_length=36, null=True, verbose_name='kibana_system')),
                ('apmPwd', models.CharField(blank=True, max_length=36, null=True, verbose_name='apm_system')),
                ('logstashPwd', models.CharField(blank=True, max_length=36, null=True, verbose_name='logstash_system')),
                ('beatsPwd', models.CharField(blank=True, max_length=36, null=True, verbose_name='beats_system')),
                ('remoteMonitoringPwd', models.CharField(blank=True, max_length=36, null=True, verbose_name='remote_monitoring_user')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.server', verbose_name='服务器')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DbServiceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(max_length=32, null=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('hasRootPriority', models.BooleanField(blank=True, default=False, verbose_name='拥有root权限')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属个体/组织')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.dbservice', verbose_name='服务器')),
            ],
            options={
                'verbose_name': '数据库用户',
                'verbose_name_plural': '所有数据库用户',
            },
        ),
        migrations.AddField(
            model_name='dbservice',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.server', verbose_name='服务器'),
        ),
        migrations.CreateModel(
            name='BT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('port', models.PositiveIntegerField(default=8888, verbose_name='端口')),
                ('username', models.CharField(help_text='请输入用户名', max_length=32, null=True, verbose_name='用户')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('basicAuthUsername', models.CharField(blank=True, max_length=32, null=True, verbose_name='BasicAuth用户')),
                ('basicAuthPwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='BasicAuth密码')),
                ('path', models.CharField(blank=True, max_length=50, null=True, verbose_name='面板路径')),
                ('domain', models.URLField(blank=True, null=True, verbose_name='绑定的域名')),
                ('server', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.server', verbose_name='宿机')),
            ],
            options={
                'verbose_name': '宝塔',
                'verbose_name_plural': '所有宝塔',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(max_length=40, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='账号归属')),
                ('url', models.URLField(blank=True, null=True, verbose_name='网站地址')),
                ('emails', models.ManyToManyField(blank=True, related_name='emails', to='accountApp.Email', verbose_name='所有绑定的电子邮箱')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属')),
                ('platform', models.ForeignKey(limit_choices_to=models.Q(('url__isnull', False)), null=True, on_delete=django.db.models.deletion.CASCADE, related_name='platform', to='accountApp.type', verbose_name='所属平台')),
                ('tels', models.ManyToManyField(blank=True, related_name='tels', to='accountApp.Tel', verbose_name='所有绑定的手机号')),
                ('types', models.ManyToManyField(blank=True, limit_choices_to=models.Q(('url__isnull', True)), related_name='accountTypes', to='accountApp.Type', verbose_name='类型')),
                ('wechat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.wechat', verbose_name='绑定的微信')),
            ],
            options={
                'verbose_name': '通用账号',
                'verbose_name_plural': '所有通用账号',
            },
        ),
    ]
