# Generated by Django 3.2.12 on 2022-11-28 04:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='enterprices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='企业/分类名')),
            ],
            options={
                'verbose_name': '企业/分类',
                'verbose_name_plural': '企业/分类',
            },
        ),
        migrations.CreateModel(
            name='parentMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='菜单名')),
                ('icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
            ],
            options={
                'verbose_name': '账号菜单',
                'verbose_name_plural': '账号菜单',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200, verbose_name='账号')),
                ('Pwd', models.CharField(max_length=200, verbose_name='密码')),
                ('ipAddres', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口号')),
                ('Platform', models.CharField(blank=True, max_length=100, null=True, verbose_name='平台')),
                ('remarks', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
                ('Links', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('BasicAuthUser', models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicAuth用户名')),
                ('BasicAuthPwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='BasicAuth密码')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('ParentMenu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountApp.parentmenu', verbose_name='账号类型')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
                ('enterprice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accountApp.enterprices', verbose_name='企业/分类')),
            ],
            options={
                'verbose_name': '所有账号',
                'verbose_name_plural': '所有账号',
                'ordering': ['id'],
            },
        ),
    ]
