# Generated by Django 3.2.12 on 2023-02-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='bt',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='city',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='country',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='dbservice',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='dbserviceuser',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='elasticsearch',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='email',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='human',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='server',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='serveruser',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='subdivision',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='tel',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='type',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
        migrations.AlterField(
            model_name='wechat',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='说明'),
        ),
    ]
