# Generated by Django 3.2.12 on 2023-02-13 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_auto_20230213_0307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elasticsearch',
            options={'verbose_name': 'Searches', 'verbose_name_plural': 'ElasticSearches'},
        ),
    ]
