# Generated by Django 3.2.12 on 2023-04-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0002_alter_server_hoster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wechat',
            name='nickName',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='微信名（可忽略）'),
        ),
    ]
