# Generated by Django 3.2.12 on 2023-02-13 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_alter_elasticsearch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='说明')),
                ('cardNumber', models.CharField(db_index=True, max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='卡号')),
                ('withdrawalPwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='取款密码')),
                ('E_bankingPwd', models.CharField(blank=True, max_length=32, null=True, verbose_name='网银密码')),
                ('affiliatedBank', models.PositiveSmallIntegerField(choices=[(1, '中国工商银行'), (2, '中国建设银行'), (3, '中国交通银行'), (4, '中国招商银行')], null=True, verbose_name='所属银行')),
                ('bankCardType', models.PositiveSmallIntegerField(choices=[(1, '中国工商银行'), (2, '中国建设银行'), (3, '中国交通银行'), (4, '中国招商银行')], null=True, verbose_name='银行卡类型')),
                ('remark', models.CharField(blank=True, max_length=100, null=True, verbose_name='备注')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属账号组')),
                ('tel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.tel', verbose_name='绑定的手机号')),
            ],
            options={
                'verbose_name': '银行',
                'verbose_name_plural': '所有银行',
            },
        ),
    ]
