# Generated by Django 3.2.12 on 2023-04-03 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0003_alter_wechat_nickname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankCardModels',
            new_name='BankCard',
        ),
    ]
