# Generated by Django 3.2.12 on 2023-02-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_bankcard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BankCard',
            new_name='BankCardModels',
        ),
    ]
