# Generated by Django 3.2.12 on 2023-04-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0004_rename_bankcardmodels_bankcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tel',
            name='appPwd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='app登录密码'),
        ),
    ]
