# Generated by Django 3.2.12 on 2023-05-14 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0005_alter_tel_apppwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='ip',
            field=models.GenericIPAddressField(help_text='可以是IPV4/IPV6', verbose_name='IP地址'),
        ),
    ]
