# Generated by Django 3.2.12 on 2023-02-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0005_rename_bankcard_bankcardmodels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcardmodels',
            options={'verbose_name': '银行卡', 'verbose_name_plural': '所有银行卡'},
        ),
        migrations.AlterField(
            model_name='bankcardmodels',
            name='bankCardType',
            field=models.PositiveSmallIntegerField(choices=[(1, '存储卡'), (2, '信用卡')], null=True, verbose_name='银行卡类型'),
        ),
    ]
