# Generated by Django 3.2.12 on 2023-05-24 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0006_alter_server_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(blank=True, help_text='如您不是wifi管理员则不用填写！', max_length=40, null=True, verbose_name='管理员账号')),
                ('pwd', models.CharField(blank=True, help_text='如您不是wifi管理员则不用填写!', max_length=32, null=True, verbose_name='密码')),
                ('name', models.CharField(max_length=100, verbose_name='WIFI名')),
                ('wifiPwd', models.CharField(max_length=32, null=True, verbose_name='WIFI密码')),
                ('isAdmin', models.BooleanField(verbose_name='是否是管理员')),
                ('LAA', models.CharField(help_text='如您不是wifi管理员则不用填写！', max_length=100, null=True, verbose_name='管理地址')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属')),
            ],
            options={
                'verbose_name': 'Wifi管理',
                'verbose_name_plural': '所有Wifi管理',
            },
        ),
    ]
