# Generated by Django 3.2.12 on 2023-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0007_wifi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wifi',
            name='LAA',
            field=models.CharField(blank=True, help_text='如您不是wifi管理员则不用填写！', max_length=100, null=True, verbose_name='管理地址'),
        ),
    ]
