# Generated by Django 3.2.12 on 2023-06-01 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0008_alter_wifi_laa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True, null=True, verbose_name='创建时间')),
                ('updatedAt', models.DateTimeField(auto_now=True, db_index=True, null=True, verbose_name='最近更新时间')),
                ('deletedAt', models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='被删除时间')),
                ('info', models.TextField(blank=True, null=True, verbose_name='说明')),
                ('username', models.CharField(max_length=40, null=True, verbose_name='管理账号')),
                ('pwd', models.CharField(max_length=32, null=True, verbose_name='管理密码')),
                ('name', models.CharField(max_length=200, verbose_name='项目名')),
                ('LAA', models.CharField(blank=True, help_text='如项目无后台可咱不填写！', max_length=200, null=True, verbose_name='后台地址')),
                ('ForegroundAddress', models.CharField(blank=True, help_text='如项目无前台可咱不填写！', max_length=200, null=True, verbose_name='前台地址')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.human', verbose_name='所属')),
            ],
            options={
                'verbose_name': '项目管理',
                'verbose_name_plural': '所有项目管理',
            },
        ),
    ]
