# Generated by Django 3.2.12 on 2023-06-01 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0009_projectmodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodels',
            name='db',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.dbservice', verbose_name='绑定数据库'),
        ),
        migrations.AddField(
            model_name='projectmodels',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accountApp.server', verbose_name='绑定服务器'),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='pwd',
            field=models.CharField(max_length=32, null=True, verbose_name='后台管理密码'),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='username',
            field=models.CharField(max_length=40, null=True, verbose_name='后台管理账号'),
        ),
    ]
