# Generated by Django 3.2.12 on 2023-06-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0010_auto_20230601_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='ForegroundAddress',
            field=models.CharField(blank=True, help_text='如项目无前台可暂不填写！', max_length=200, null=True, verbose_name='前台地址'),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='LAA',
            field=models.CharField(blank=True, help_text='如项目无后台可暂不填写！', max_length=200, null=True, verbose_name='后台地址'),
        ),
    ]
