# Generated by Django 3.2.12 on 2023-06-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountApp', '0011_auto_20230601_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodels',
            name='pwd',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='后台管理密码'),
        ),
        migrations.AlterField(
            model_name='projectmodels',
            name='username',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='后台管理账号'),
        ),
    ]
